services:
  db:
    container_name: WebAppDB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=news
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
    image: postgres:15.5-alpine3.18