POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "id": "1",
  "login": "alexander",
  "pass": "1234",
  "coder": "MD2"
}
###
POST http://127.0.0.1:8080/api/auth/login
Content-Type: application/json

{
  "login": "admin",
  "password": "1234"
}
###
POST http://127.0.0.1:8080/api/auth/logout
Accept: application/json